apiVersion: v1
kind: Service
metadata:
  name: pma
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  ports:
  - port : 5000
    targetPort: 5000
  selector:
    app: pma
  type: LoadBalancer
  loadBalancerIP: 192.168.49.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: pm
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - image: pma
        name: pma
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: pma
        volumeMounts:
        - name: pma-config
          mountPath: /etc/nginx/http.d/
          readOnly: true
      volumes:
      - name: pma-config
        configMap:
          name: pma-config
