apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  ports:
  - port : 5050
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.49.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wp-ps
          mountPath: /wordpress/files
        - name: wp-config
          mountPath: /etc/nginx/http.d/
          readOnly: true
      volumes:
      - name: wp-ps
        persistentVolumeClaim:
          claimName: wp-pv-claim
      - name: wp-config
        configMap:
          name: wp-config
